---
cloud_service_group: Network
cloud_service_type: VirtualNetwork
name: Subnet Count per Subscription
query:
  aggregate:
   - unwind:
       path: data.subnets
   - group:
       keys:
       - name: name
         key: account
       fields:
        - name: value
          key: account
          operator: count
options:
  chart_type: DONUT
