---
cloud_service_group: Network
cloud_service_type: VirtualNetwork
name: Subnet Count per Location
query:
  aggregate:
   - unwind:
       path: data.subnets
   - group:
       keys:
       - name: name
         key: region_code
       fields:
        - name: value
          key: region_code
          operator: count
options:
  chart_type: COLUMN
