---
cloud_service_group: Network
cloud_service_type: LoadBalancer
name: Loadbalancer Backend Pool VM Count per Location
query:
  aggregate:
   - unwind:
       path: data.network_interfaces
   - group:
       keys:
       - name: location
         key: data.network_interfaces.location
       fields:
        - name: count
          key: data.network_interfaces.location
          operator: count
options:
  chart_type: COLUMN
