---
cloud_service_group: Compute
cloud_service_type: VmScaleSet
name: VmScaleSet Total Count per Subscription
query:
  aggregate:
   - group:
       fields:
         - name: value
           key: data.instance_count
           operator: sum
