---
cloud_service_group: KeyVault
cloud_service_type: KeyVault
name: KeyVault Total Count per Subscription
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: account
        fields:
          - name: value
            key: account
            operator: count
options:
  chart_type: DONUT
