---
cloud_service_group: KeyVault
cloud_service_type: KeyVault
name: KeyVault Total Count per Location
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: region_code
        fields:
          - name: value
            key: region_code
            operator: count
options:
  chart_type: COLUMN
