---
cloud_service_group: Database
cloud_service_type: SQLDatabase
name: SQLDatabase Total Count per Server
query:
  aggregate:
    - unwind:
        path: data.databases
    - group:
        keys:
          - name: server_name
            key: data.databases.server_name
        fields:
          - name: count
            key: data.databases.server_name
            operator: count
options:
  chart_type: COLUMN
