---
cloud_service_group: Database
cloud_service_type: SQLDatabase
name: SQLServer Total Count per Location
query:
  aggregate:
    - group:
        keys:
          - name: region_code
            key: region_code
        fields:
          - name: location
            key: region_code
            operator: count
options:
  chart_type: COLUMN
