---
cloud_service_group: Compute
cloud_service_type: Snapshot
name: Snapshot Total Count per Subscription
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: account
        fields:
          - name: value
            operator: count
options:
  chart_type: DONUT
