---
cloud_service_group: Compute
cloud_service_type: Snapshot
name: Snapshot Total Count per Resource Group
query:
  aggregate:
   - group:
       keys:
        - name: resource_group
          key: data.resource_group
       fields:
        - name: value
          key: data.resource_group
          operator: count
options:
  chart_type: DONUT
