---
cloud_service_group: Storage
cloud_service_type: StorageAccount
name: StorageAccount Total Count per Location
query:
  aggregate:
    - group:
        keys:
          - name: region_code
            key: region_code
        fields:
          - name: value
            key: region_code
            operator: count
options:
  chart_type: COLUMN
