---
cloud_service_group: Network
cloud_service_type: NetworkSecurityGroup
name: NetworkSecurityGroup Total Count per Subscription
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: account
        fields:
          - name: value
            key: account
            operator: count
options:
  chart_type: DONUT
