---
cloud_service_group: Network
cloud_service_type: NetworkSecurityGroup
name: NetworkSecurityGroup Total Count per Location
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: region_code
        fields:
          - name: value
            key: region_code
            operator: count
options:
  chart_type: COLUMN
