---
cloud_service_group: Database
cloud_service_type: PostgreSQLServer
name: PostgreSQLServer Total Count per Subscription
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: account
        fields:
          - name: value
            key: account
            operator: count
options:
  chart_type: DONUT
