---
cloud_service_group: Database
cloud_service_type: AzureCosmosDB
name: AzureCosmosDB Total Count per Location
query:
  aggregate:
    - unwind:
        path: data.sql_databases
    - group:
        keys:
          - name: name
            key: data.name
        fields:
          - name: count
            key: data.sql_databases
            operator: count
options:
  chart_type: COLUMN
