---
cloud_service_group: Compute
cloud_service_type: Disk
name: Disk Total Size per Subscription
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: account
        fields:
          - name: value
            key: instance_size
            operator: sum
options:
  chart_type: COLUMN
